iam:
  roles:
    - name: DatabricksIAMRole
      assume_role_policy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {"Service": "ec2.amazonaws.com"},
              "Action": "sts:AssumeRole"
            }
          ]
        }
      policies:
        - arn: "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - arn: "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
  outputs:
    role_arns: []

# IAM Resource Class
import pulumi_aws as aws
from dto import IAMConfigDTO

class IAMResource:
    def __init__(self, config: IAMConfigDTO):
        self.config = config
        self.setup_roles()

    def setup_roles(self):
        for role in self.config.roles:
            iam_role = aws.iam.Role(
                role.name,
                assume_role_policy=role.assume_role_policy
            )
            for policy_arn in role.policies:
                aws.iam.RolePolicyAttachment(
                    f"{role.name}-{policy_arn.split('/')[-1]}",
                    role=iam_role.name,
                    policy_arn=policy_arn
                )
            # Capture the ARN of the created role in the DTO
            if 'role_arns' not in self.config.outputs:
                self.config.outputs['role_arns'] = []
            self.config.outputs['role_arns'].append(iam_role.arn)

    def output_dto(self) -> IAMConfigDTO:
        return self.config

#
